### ISSUE TITLE
finetuning on larger dataset

### ISSUE THREAD

**Issue by sinhprous** [gmltmd789/UnitSpeech#3]
I tried the colab, seems that when finetuning it only uses one reference sample.
Can I use a larger dataset (contains hundreds of reference samples) to fine-tune the model? will it affect the model's performance?
Thanks.

**Comment by gmltmd789** [comment]
Hello,

Unfortunately, the current code does not support fine-tuning using multiple samples. If you wish to perform fine-tuning with multiple samples, you will need to make some modifications to the code in the fine-tuning section.

When using only one sample, it is occasionally observed that the quality of the output, such as audio quality or speaker similarity, can be unstable depending on the reference speech.

We expect that using more samples will allow for a more stable acquisition of audio quality and speaker similarity.
