### ISSUE TITLE
Can I fine tune Text Encoder in other languages ?

### ISSUE THREAD

**Issue by rishikksh20** [gmltmd789/UnitSpeech#4]
@gmltmd789 I have one question
As Decoder working great to adapt on non english speaker, For training TTS for non-english language is it possible to just train pretrained Text Encoder on `Lgrad` and `Lenc` by freezing Decoder part ?
I don't think I have to train Unit Encoder as it already trained on mHuBERT.

**Comment by unitspeech** [comment]
Hello,

Regarding your inquiry, we are currently conducting experiments internally using the text encoder tuning approach for multiple languages.

Once these experiments are completed, we plan to release the code that allows for multi-lingual expansion, along with the training code for the model.

Thank you for your interest.

**Comment by rishikksh20** [comment]
I am also working to finetune Text Encoder and MAS duration predictor for different languages.
