### ISSUE TITLE
Pre-training code

### ISSUE THREAD

**Issue by gvamvou** [gmltmd789/UnitSpeech#5]
Hello! Great work, I really enjoyed the presentation at Interspeech. Is it possible to train the models from scratch? Is there the pre-training code available or are there any plans to release it in the future?
Thanks for your time.

**Comment by gmltmd789** [comment]
Hello,
First of all, thank you for your interest!
We are currently preparing a multi-lingual version.
We plan to include the training code when we release this version!

**Comment by gvamvou** [comment]
Thanks for your response! I look forward to it.

**Comment by gvamvou** [comment]
Thanks for your response! Looking forward to it!
