### ISSUE TITLE
Can you provide the decoder after fine-tuning?

### ISSUE THREAD

**Issue by ZXHY-82** [gmltmd789/UnitSpeech#7]
Can you provide the decoder after fine-tuning?

**Comment by gmltmd789** [comment]
Hi,

Fine-tuning involves the decoder adapting based on references provided by individual users. 

Consequently, it is challenging to provide a fine-tuned decoder for a specific target speaker, as it varies with each reference that user provided.

Following the process in the repository will allow you to obtain a fine-tuned decoder easily and quickly. I recommend checking it out for guidance!
