### ISSUE TITLE
How to extract units?

### ISSUE THREAD

**Issue by huangf79** [gmltmd789/UnitSpeech#8]
Thank you for sharing this excellent work. How should I extract hubert units if I want to train a new unit encoder? And which layer of features did you use?

**Comment by gmltmd789** [comment]
Hi,

You can extract hubert units by the code below!

```
print('Initializing Unit Extracter...')
dense_model_name = "mhubert-base-vp_en_es_fr"
quantizer_name, vocab_size = "kmeans", 1000

unit_extractor = SpeechEncoder.by_name(
        dense_model_name=dense_model_name,
        quantizer_model_name=quantizer_name,
        vocab_size=vocab_size,
        deduplicate=True,
        need_f0=False
    )
_ = unit_extractor.cuda().eval()

wav, sr = librosa.load(args.reference_path)
wav = torch.FloatTensor(wav).unsqueeze(0)
resample_fn = torchaudio.transforms.Resample(sr, 16000).cuda()
wav = resample_fn(wav.cuda())

encoded = unit_extractor(wav.to("cuda"))

unit, duration = process_unit(encoded, hps.data.sampling_rate, hps.data.hop_length)
```

You can also find this code in scripts/finetune.py.

**Comment by huangf79** [comment]
Thanks! Is this the same hubert you used in the paper? And it seems that the output layer of features were not mentioned.

**Comment by gmltmd789** [comment]
We use mHuBERT, layer 11 in this site.
[https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_speech/docs/textless_s2st_real_data.md](url)
We observe that there is almost no difference between the unit above and the unit used in the paper, so you can use what you want.

**Comment by huangf79** [comment]
I get it. Thanks a lot!
